name: Lint

on:
  - push
  - pull_request

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Setup corepack
        run: corepack enable
      - uses: bahmutov/npm-install@v1
        with:
          install-command: pnpm install

      - name: Build
        run: |
          pnpm run prepare

      - name: Lint files
        run: pnpm run lint:eslint

  biome:
    name: biome
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Setup corepack
        run: corepack enable
      - uses: bahmutov/npm-install@v1
        with:
          install-command: pnpm install

      - name: Build
        run: |
          pnpm run prepare

      - name: Lint files
        run: pnpm run lint:biome

  types:
    name: biome
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Setup corepack
        run: corepack enable
      - uses: bahmutov/npm-install@v1
        with:
          install-command: pnpm install

      - name: Build
        run: |
          pnpm run prepare

      - name: Typecheck files
        run: pnpm run lint:types

  knip:
    name: knip
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Setup corepack
        run: corepack enable
      - uses: bahmutov/npm-install@v1
        with:
          install-command: pnpm install

      - name: Check for unused things
        run: pnpm run knip
